-- zad1
SELECT IMIE_WROGA "WROG", OPIS_INCYDENTU "PRZEWINA"
FROM Wrogowie_kocurow
WHERE DATA_INCYDENTU BETWEEN '2009-01-01' AND '2009-12-31';
-- zad2
SELECT IMIE, FUNKCJA, W_STADKU_OD "Z NAMI OD"
FROM KOCURY
WHERE PLEC='D' AND W_STADKU_OD BETWEEN '2005-09-01' AND '2007-07-31';
-- zad3
SELECT IMIE_WROGA "WROG", GATUNEK, STOPIEN_WROGOSCI "STOPIEN WROGOSCI"
FROM Wrogowie
WHERE LAPOWKA IS NULL
ORDER BY STOPIEN_WROGOSCI;
-- zad4
SELECT IMIE || ' zwany ' || PSEUDO || ' (fun. ' || FUNKCJA || ')' || ' lowi myszki w bandzie ' || NR_BANDY || ' od ' || W_STADKU_OD
"WSZYSTKO O KOCURACH"
FROM KOCURY
WHERE PLEC='M'
ORDER BY W_STADKU_OD DESC, PSEUDO ASC;
-- zad5
SELECT PSEUDO, REGEXP_REPLACE(REGEXP_REPLACE(PSEUDO, 'A', '#', 1, 1), 'L', '%', 1, 1) "Po wymianie A na # oraz L na %"
FROM KOCURY
WHERE PSEUDO LIKE '%A%L%' OR  PSEUDO LIKE '%L%A%';
-- zad6
SELECT IMIE, W_STADKU_OD "W stadku", ROUND(NVL(PRZYDZIAL_MYSZY,0)/1.1) "Zjadał", ADD_MONTHS(W_STADKU_OD, 6) "Podwyzka", NVL(PRZYDZIAL_MYSZY, 0) "Zjada"
FROM KOCURY 
WHERE EXTRACT(MONTH FROM W_STADKU_OD) BETWEEN 3 AND 9
AND MONTHS_BETWEEN(SYSDATE, W_STADKU_OD)>= 13*2;
-- zad7
SELECT IMIE, NVL(PRZYDZIAL_MYSZY,0)*3 "MYSZY KWARTALNIE", NVL(MYSZY_EXTRA, 0)*3 "KWARTALNE DODATKI" 
FROM Kocury
WHERE NVL(PRZYDZIAL_MYSZY, 0) > NVL(MYSZY_EXTRA, 0)*2 AND NVL(PRZYDZIAL_MYSZY, 0) >= 55
ORDER BY NVL(MYSZY_EXTRA, 0)*3 DESC;
-- zad8
SELECT IMIE, 
CASE
    WHEN (NVL(PRZYDZIAL_MYSZY, 0) + NVL(MYSZY_EXTRA, 0)) * 12  < 660 THEN 'Poniżej 660'
    WHEN (NVL(PRZYDZIAL_MYSZY, 0) + NVL(MYSZY_EXTRA, 0)) * 12  = 660 THEN 'Limit'
    ELSE TO_CHAR((NVL(PRZYDZIAL_MYSZY, 0) + NVL(MYSZY_EXTRA, 0)) * 12)
END "Zjada rocznie"
FROM KOCURY;
-- zad9
SELECT PSEUDO, W_STADKU_OD "W STADKU", 
CASE
    WHEN (EXTRACT(DAY FROM W_STADKU_OD) BETWEEN 1 AND 15) THEN CASE 
        WHEN NEXT_DAY(LAST_DAY(TO_DATE('2022-10-25')) - 7, 'WEDNESDAY') < TO_DATE('2022-10-25') THEN NEXT_DAY(LAST_DAY(ADD_MONTHS(TO_DATE('2022-10-25'),1)) - 7, 'WEDNESDAY')
        ELSE NEXT_DAY(LAST_DAY(TO_DATE('2022-10-25')) - 7, 'WEDNESDAY')
        END
    ELSE NEXT_DAY(LAST_DAY(ADD_MONTHS(TO_DATE('2022-10-25'), 1)) - 7, 'WEDNESDAY')
END "Wypłata"
FROM KOCURY;

SELECT PSEUDO, W_STADKU_OD "W STADKU", 
CASE
    WHEN (EXTRACT(DAY FROM W_STADKU_OD) BETWEEN 1 AND 15) THEN CASE 
        WHEN NEXT_DAY(LAST_DAY(TO_DATE('2022-10-27')) - 7, 'WEDNESDAY') < TO_DATE('2022-10-27') THEN NEXT_DAY(LAST_DAY(ADD_MONTHS(TO_DATE('2022-10-27'),1)) - 7, 'WEDNESDAY')
        ELSE NEXT_DAY(LAST_DAY(TO_DATE('2022-10-27')) - 7, 'WEDNESDAY')
        END
    ELSE NEXT_DAY(LAST_DAY(ADD_MONTHS(TO_DATE('2022-10-27'), 1)) - 7, 'WEDNESDAY')
END "Wypłata"
FROM KOCURY;
-- zad10
SELECT DECODE(COUNT(PSEUDO), 1, PSEUDO || ' - Unikalny', PSEUDO || ' - nieunikalny') "Unikalnosc atr. PSEUDO"
FROM KOCURY
GROUP BY PSEUDO;

SELECT DECODE(COUNT(PSEUDO), 1, SZEF || ' - Unikalny', SZEF || ' - nieunikalny') "Unikalnosc atr. SZEF"
FROM KOCURY
WHERE SZEF IS NOT NULL
GROUP BY SZEF;
-- zad11
SELECT PSEUDO "Pseudonim", COUNT(PSEUDO) "Liczba wrogow"
FROM WROGOWIE_KOCUROW
GROUP BY PSEUDO
HAVING COUNT(PSEUDO) > 1;
-- zad12
SELECT 'Liczba kotow= ' || COUNT(FUNKCJA) || ' lowi jako ' || FUNKCJA || ' i zjada max. ' || MAX(NVL(PRZYDZIAL_MYSZY,0) + NVL(MYSZY_EXTRA,0)) || ' myszy miesiecznie' " " 
FROM KOCURY
WHERE FUNKCJA != 'SZEFUNIO' AND PLEC != 'M'
GROUP BY FUNKCJA
HAVING MAX(NVL(PRZYDZIAL_MYSZY,0) + NVL(MYSZY_EXTRA,0)) > 50;
-- zad13
SELECT NR_BANDY "Nr bandy", PLEC "Plec", MIN(NVL(PRZYDZIAL_MYSZY, 0)) "Minimalny przydział" 
FROM KOCURY
GROUP BY NR_BANDY, PLEC;
-- zad14
SELECT level "Poziom", PSEUDO "Pseudonim", FUNKCJA "Funkcja", NR_BANDY "Nr bandy"
FROM KOCURY
WHERE PLEC = 'M'
CONNECT BY PRIOR PSEUDO = SZEF
START WITH FUNKCJA = 'BANDZIOR';
-- zad15
SELECT 
    LPAD(level-1, 4*(level-1)+1, '===>') || '    ' ||IMIE "Hierarchia", 
    NVL( SZEF, 'Sam sobie szefem') "Pseudo szefa",
    FUNKCJA "Funkcja"
FROM KOCURY
WHERE MYSZY_EXTRA IS NOT NULL
CONNECT BY PRIOR PSEUDO = SZEF
START WITH SZEF IS NULL;
-- zad16
SELECT LPAD(' ', 4*(level-1)) || PSEUDO "Droga służbowa"
FROM KOCURY
CONNECT BY PRIOR SZEF = PSEUDO
START WITH PLEC = 'M' AND (DATE '2022-07-14' - W_STADKU_OD) >= 4745 AND MYSZY_EXTRA IS NULL;